/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordealuguellivros;

/**
 *
 * @author Matthews
 */
public class Aluguel extends javax.swing.JFrame {

    /**
     * Creates new form Aluguel
     */
    public Aluguel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelEstudo = new javax.swing.JLabel();
        jLabelLivro1 = new javax.swing.JLabel();
        jLabelLivro2 = new javax.swing.JLabel();
        jLabelLivro3 = new javax.swing.JLabel();
        jLabelLivro4 = new javax.swing.JLabel();
        jLabelLivro5 = new javax.swing.JLabel();
        jLabelLivro6 = new javax.swing.JLabel();
        jLabelLivro7 = new javax.swing.JLabel();
        jLabelLivro8 = new javax.swing.JLabel();
        jLabelLivro9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonProxima = new javax.swing.JButton();
        jLabelRes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEstudo = new javax.swing.JTextArea();
        jLabelALuguelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 390, 90, 40);

        jLabelEstudo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEstudo.setText("Estante de Estudos");
        getContentPane().add(jLabelEstudo);
        jLabelEstudo.setBounds(300, 10, 190, 30);

        jLabelLivro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro1.setForeground(new java.awt.Color(0, 0, 102));
        jLabelLivro1.setText("Livro 1: Fisica Aplicada a Computação");
        getContentPane().add(jLabelLivro1);
        jLabelLivro1.setBounds(270, 50, 270, 30);

        jLabelLivro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro2.setForeground(new java.awt.Color(0, 0, 102));
        jLabelLivro2.setText("Livro 2: Logica Aplicada ");
        getContentPane().add(jLabelLivro2);
        jLabelLivro2.setBounds(270, 90, 200, 17);

        jLabelLivro3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro3.setForeground(new java.awt.Color(0, 0, 102));
        jLabelLivro3.setText("Livro 3: Algebra Linear");
        getContentPane().add(jLabelLivro3);
        jLabelLivro3.setBounds(270, 120, 170, 17);

        jLabelLivro4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro4.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro4.setText("Livro 4: Programação Orientada a Objeto ");
        getContentPane().add(jLabelLivro4);
        jLabelLivro4.setBounds(270, 140, 300, 30);

        jLabelLivro5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro5.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro5.setText("Livro 5: Programação em C e C ++");
        getContentPane().add(jLabelLivro5);
        jLabelLivro5.setBounds(270, 180, 280, 20);

        jLabelLivro6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro6.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro6.setText("Livro 6: Programação em Python");
        getContentPane().add(jLabelLivro6);
        jLabelLivro6.setBounds(270, 210, 270, 17);

        jLabelLivro7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro7.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro7.setText("Livro 7: Programação em Javascript");
        getContentPane().add(jLabelLivro7);
        jLabelLivro7.setBounds(270, 240, 260, 20);

        jLabelLivro8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro8.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro8.setText("Livro 8: Criando Aplicativos Android");
        getContentPane().add(jLabelLivro8);
        jLabelLivro8.setBounds(270, 270, 260, 17);

        jLabelLivro9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro9.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro9.setText("Livro 9: Banco de Dados com MySql e PostgreSql");
        getContentPane().add(jLabelLivro9);
        jLabelLivro9.setBounds(270, 300, 340, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Livro 10: PHP, HTML e CSS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 330, 340, 17);

        jButtonProxima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProxima.setText("Proxima");
        jButtonProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProxima);
        jButtonProxima.setBounds(560, 390, 100, 40);

        jLabelRes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRes.setForeground(new java.awt.Color(255, 0, 255));
        jLabelRes.setText("Resumo Estudos:");
        getContentPane().add(jLabelRes);
        jLabelRes.setBounds(20, 20, 110, 15);

        jTextAreaEstudo.setColumns(20);
        jTextAreaEstudo.setRows(5);
        jTextAreaEstudo.setText("Livros para estudantes\nDa área de tecnologia da \ninformação\n");
        jTextAreaEstudo.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaEstudo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 210, 120);

        jLabelALuguelFundo.setIcon(new javax.swing.ImageIcon("D:\\JAVA PRO\\livros abertos.jpg")); // NOI18N
        getContentPane().add(jLabelALuguelFundo);
        jLabelALuguelFundo.setBounds(0, 0, 740, 460);

        setSize(new java.awt.Dimension(755, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximaActionPerformed
        ListaLivros lista = new ListaLivros();
        lista.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonProximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonProxima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelALuguelFundo;
    private javax.swing.JLabel jLabelEstudo;
    private javax.swing.JLabel jLabelLivro1;
    private javax.swing.JLabel jLabelLivro2;
    private javax.swing.JLabel jLabelLivro3;
    private javax.swing.JLabel jLabelLivro4;
    private javax.swing.JLabel jLabelLivro5;
    private javax.swing.JLabel jLabelLivro6;
    private javax.swing.JLabel jLabelLivro7;
    private javax.swing.JLabel jLabelLivro8;
    private javax.swing.JLabel jLabelLivro9;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEstudo;
    // End of variables declaration//GEN-END:variables
}
