/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordealuguellivros;

import Gerenciador.ConexaoBD;
import Gerenciador.ControleUsuario;
import Modelo.ModeloTabela;
import Modelo.ModeloUsuario;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matthews
 */
public class Cadastro extends javax.swing.JFrame {

    ModeloUsuario mod = new ModeloUsuario();
    ControleUsuario control = new ControleUsuario();
    ConexaoBD conex = new ConexaoBD();
    int flag =0;
    
    
    public Cadastro() {
        initComponents();
        preencherTabela("select *from usuario order by nome_usuario");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonVoltar2 = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaUsuarios = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxLivros = new javax.swing.JComboBox();
        jLabelLivro = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jLabelFundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Nome de usuario: ");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(10, 50, 130, 30);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(140, 50, 230, 30);

        jButtonVoltar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar2.setText("Voltar");
        jButtonVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar2);
        jButtonVoltar2.setBounds(420, 360, 80, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(420, 280, 80, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(420, 320, 80, 30);

        jTableTabelaUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableTabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaUsuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 400, 190);
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(0, 230, 200, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 230, 100, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(30, 140, 80, 30);

        jComboBoxLivros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxLivros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));
        jComboBoxLivros.setEnabled(false);
        jComboBoxLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLivrosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLivros);
        jComboBoxLivros.setBounds(80, 90, 190, 30);

        jLabelLivro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro.setText("Livro:");
        getContentPane().add(jLabelLivro);
        jLabelLivro.setBounds(10, 100, 90, 20);

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(0, 0, 153));
        jLabelValor.setText("Valor de cada aluguel é 5 reais");
        getContentPane().add(jLabelValor);
        jLabelValor.setBounds(350, 190, 220, 40);

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigo.setText("Codigo");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(80, 20, 80, 17);

        jTextFieldCodigo.setEnabled(false);
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(140, 10, 90, 30);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(130, 140, 80, 30);

        jLabelFundoCadastro.setIcon(new javax.swing.ImageIcon("D:\\JAVA PRO\\O-Cadastro-de-Produtos-como-um-diferencial-competitivo-2-1.png")); // NOI18N
        getContentPane().add(jLabelFundoCadastro);
        jLabelFundoCadastro.setBounds(-70, 0, 840, 490);

        setSize(new java.awt.Dimension(739, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltar2ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltar2ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if(flag==1){
        mod.setNome(jTextFieldNome.getText());
        mod.setLivros(jComboBoxLivros.getSelectedIndex());
        mod.setValor(5);
        control.Salvar(mod);
        jTextFieldNome.setText("");
        jTextFieldNome.setEnabled(false);
        jComboBoxLivros.setEnabled(false);
        jButtonSalvar.setEnabled(false);
       
        }else{
            mod.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
            mod.setNome(jTextFieldNome.getText());
            mod.setLivros((Integer)jComboBoxLivros.getSelectedIndex());
            mod.setValor(5);
            control.Editar(mod);
            jTextFieldCodigo.setText("");
            jTextFieldNome.setText("");
            jTextFieldNome.setEnabled(false);
            jComboBoxLivros.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisa(jTextFieldPesquisa.getText());
        ModeloUsuario model = control.buscaUsuario(mod);
        jTextFieldCodigo.setText(String.valueOf(model.getCodigo()));
        jTextFieldNome.setText(model.getNome());
        jComboBoxLivros.setSelectedIndex(model.getLivros());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jComboBoxLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLivrosActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag=2;
        jTextFieldNome.setEnabled(true);
        jComboBoxLivros.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag= 1;
        jTextFieldNome.setEnabled(true);
        jComboBoxLivros.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            mod.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
            control.Excluir(mod);
            
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableTabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaUsuariosMouseClicked
        String nome_usuario =""+jTableTabelaUsuarios.getValueAt(jTableTabelaUsuarios.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select *from usuario where nome_usuario='"+nome_usuario+"'");
        try {
            conex.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conex.rs.getInt("cod_usuario")));
            jTextFieldNome.setText(conex.rs.getString("nome_usuario"));
            jComboBoxLivros.setSelectedIndex(conex.rs.getInt("livros_usuario"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar Dados\n"+ex);
            
        }
        
        conex.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableTabelaUsuariosMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String []{"Codigo","Nome de usuario", "Livro", "Valor"};
        conex.conexao();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_usuario"),conex.rs.getString("nome_usuario"),conex.rs.getInt("livros_usuario"),conex.rs.getInt("valor_em_reais")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher ArrayList"+ex);
        }       
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableTabelaUsuarios.setModel(modelo);
        jTableTabelaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableTabelaUsuarios.getColumnModel().getColumn(0).setResizable(false);
        jTableTabelaUsuarios.getColumnModel().getColumn(1).setPreferredWidth(220);
        jTableTabelaUsuarios.getColumnModel().getColumn(1).setResizable(false);
        jTableTabelaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTableTabelaUsuarios.getColumnModel().getColumn(2).setResizable(false);
        jTableTabelaUsuarios.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableTabelaUsuarios.getColumnModel().getColumn(3).setResizable(false);
        
        jTableTabelaUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableTabelaUsuarios.setAutoResizeMode(jTableTabelaUsuarios.AUTO_RESIZE_OFF);
        jTableTabelaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar2;
    private javax.swing.JComboBox jComboBoxLivros;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelFundoCadastro;
    private javax.swing.JLabel jLabelLivro;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaUsuarios;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
