/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordealuguellivros;

/**
 *
 * @author Matthews
 */
public class ListaLivros extends javax.swing.JFrame {

    /**
     * Creates new form ListaLivros
     */
    public ListaLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFic = new javax.swing.JLabel();
        jLabelLivro11 = new javax.swing.JLabel();
        jLabelLivro12 = new javax.swing.JLabel();
        jLabelLivro13 = new javax.swing.JLabel();
        jLabelLivro14 = new javax.swing.JLabel();
        jLabelLivro15 = new javax.swing.JLabel();
        jLabelLivro16 = new javax.swing.JLabel();
        jLabelLivro17 = new javax.swing.JLabel();
        jLabelNacional = new javax.swing.JLabel();
        jLabelLivro18 = new javax.swing.JLabel();
        jLabelLivro19 = new javax.swing.JLabel();
        jLabelLivro20 = new javax.swing.JLabel();
        jLabelLivro21 = new javax.swing.JLabel();
        jLabelLivro22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelInfoFic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFic = new javax.swing.JTextArea();
        jLabelResNacionais = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNacional = new javax.swing.JTextArea();
        jLabelFundoFic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelFic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFic.setText("Estante De Ficção");
        getContentPane().add(jLabelFic);
        jLabelFic.setBounds(310, 20, 190, 20);

        jLabelLivro11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro11.setForeground(new java.awt.Color(0, 0, 153));
        jLabelLivro11.setText("Livro 11: Senhor Dos Anéis A Sociedade do Anel");
        getContentPane().add(jLabelLivro11);
        jLabelLivro11.setBounds(280, 70, 360, 20);

        jLabelLivro12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro12.setForeground(new java.awt.Color(0, 51, 153));
        jLabelLivro12.setText("Livro 12:  As Duas Torres");
        getContentPane().add(jLabelLivro12);
        jLabelLivro12.setBounds(280, 100, 340, 20);

        jLabelLivro13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro13.setForeground(new java.awt.Color(0, 0, 153));
        jLabelLivro13.setText("Livro 13:  O Retorno Do Rei ");
        getContentPane().add(jLabelLivro13);
        jLabelLivro13.setBounds(280, 130, 330, 17);

        jLabelLivro14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro14.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro14.setText("Livro 14: Hobbit Uma Jornada Inesperada");
        getContentPane().add(jLabelLivro14);
        jLabelLivro14.setBounds(280, 160, 330, 17);

        jLabelLivro15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro15.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro15.setText("Livro 15:  A Desolação De Smaug");
        getContentPane().add(jLabelLivro15);
        jLabelLivro15.setBounds(280, 190, 280, 20);

        jLabelLivro16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro16.setForeground(new java.awt.Color(255, 255, 0));
        jLabelLivro16.setText("Livro 16: A Batalha Dos Cinco Exércitos ");
        getContentPane().add(jLabelLivro16);
        jLabelLivro16.setBounds(280, 220, 290, 20);

        jLabelLivro17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro17.setForeground(new java.awt.Color(51, 255, 255));
        jLabelLivro17.setText("Livro 17: O Silmarillion ");
        getContentPane().add(jLabelLivro17);
        jLabelLivro17.setBounds(280, 250, 170, 17);

        jLabelNacional.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNacional.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNacional.setText("Estante De Livros Nacionais");
        getContentPane().add(jLabelNacional);
        jLabelNacional.setBounds(270, 280, 280, 30);

        jLabelLivro18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro18.setForeground(new java.awt.Color(0, 255, 0));
        jLabelLivro18.setText("Livro 18: Quincas Borba");
        getContentPane().add(jLabelLivro18);
        jLabelLivro18.setBounds(270, 320, 340, 14);

        jLabelLivro19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro19.setForeground(new java.awt.Color(0, 255, 0));
        jLabelLivro19.setText("Livro 19: Memórias Póstumas De Brás Cubas");
        getContentPane().add(jLabelLivro19);
        jLabelLivro19.setBounds(270, 350, 350, 17);

        jLabelLivro20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro20.setForeground(new java.awt.Color(0, 255, 0));
        jLabelLivro20.setText("Livro 20: Dom Casmurro");
        getContentPane().add(jLabelLivro20);
        jLabelLivro20.setBounds(270, 380, 240, 20);

        jLabelLivro21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro21.setForeground(new java.awt.Color(0, 255, 0));
        jLabelLivro21.setText("Livro 21: O Alienista");
        getContentPane().add(jLabelLivro21);
        jLabelLivro21.setBounds(270, 410, 210, 17);

        jLabelLivro22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLivro22.setForeground(new java.awt.Color(0, 255, 0));
        jLabelLivro22.setText("Livro 22: Contos Fluminenses");
        getContentPane().add(jLabelLivro22);
        jLabelLivro22.setBounds(270, 440, 250, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 393, 100, 40);

        jLabelInfoFic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelInfoFic.setForeground(new java.awt.Color(255, 0, 255));
        jLabelInfoFic.setText("Estante de Ficção:");
        getContentPane().add(jLabelInfoFic);
        jLabelInfoFic.setBounds(20, 10, 150, 60);

        jTextAreaFic.setColumns(20);
        jTextAreaFic.setRows(5);
        jTextAreaFic.setText("Aqui está 7 volumes\ndas histórias da \nTerra-Média do autor\nTolkien ");
        jTextAreaFic.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaFic);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 230, 100);

        jLabelResNacionais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResNacionais.setForeground(new java.awt.Color(255, 0, 255));
        jLabelResNacionais.setText("Resumo de Nacionais:");
        getContentPane().add(jLabelResNacionais);
        jLabelResNacionais.setBounds(10, 230, 140, 15);

        jTextAreaNacional.setColumns(20);
        jTextAreaNacional.setRows(5);
        jTextAreaNacional.setText("Coletânea De Livros de \nMachado De Assis\npercursor do movimento\nRomatismo/Realismo no\nBrasil");
        jTextAreaNacional.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaNacional);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 260, 240, 113);

        jLabelFundoFic.setIcon(new javax.swing.ImageIcon("D:\\JAVA PRO\\livros abertos.jpg")); // NOI18N
        getContentPane().add(jLabelFundoFic);
        jLabelFundoFic.setBounds(0, -10, 770, 500);

        setSize(new java.awt.Dimension(762, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Aluguel aluguel = new Aluguel();
        aluguel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFic;
    private javax.swing.JLabel jLabelFundoFic;
    private javax.swing.JLabel jLabelInfoFic;
    private javax.swing.JLabel jLabelLivro11;
    private javax.swing.JLabel jLabelLivro12;
    private javax.swing.JLabel jLabelLivro13;
    private javax.swing.JLabel jLabelLivro14;
    private javax.swing.JLabel jLabelLivro15;
    private javax.swing.JLabel jLabelLivro16;
    private javax.swing.JLabel jLabelLivro17;
    private javax.swing.JLabel jLabelLivro18;
    private javax.swing.JLabel jLabelLivro19;
    private javax.swing.JLabel jLabelLivro20;
    private javax.swing.JLabel jLabelLivro21;
    private javax.swing.JLabel jLabelLivro22;
    private javax.swing.JLabel jLabelNacional;
    private javax.swing.JLabel jLabelResNacionais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaFic;
    private javax.swing.JTextArea jTextAreaNacional;
    // End of variables declaration//GEN-END:variables
}
