/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordealuguellivros;

import Gerenciador.ConexaoBD;


public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonAluguel = new javax.swing.JButton();
        jLabelBem = new javax.swing.JLabel();
        jLabelBB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAluguel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAluguel.setText("Lista de Livros");
        jButtonAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAluguelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAluguel);
        jButtonAluguel.setBounds(250, 360, 150, 50);

        jLabelBem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelBem.setForeground(new java.awt.Color(255, 255, 0));
        jLabelBem.setText("Bem Vindo ");
        getContentPane().add(jLabelBem);
        jLabelBem.setBounds(270, 10, 250, 70);

        jLabelBB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelBB.setForeground(new java.awt.Color(255, 255, 0));
        jLabelBB.setText("A Biblioteca Online");
        getContentPane().add(jLabelBB);
        jLabelBB.setBounds(210, 80, 360, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Escolha Umas Das Opções Abaixo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 200, 400, 70);

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(380, 440, 80, 30);

        jButtonCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastro.setText("Cadastro");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastro);
        jButtonCadastro.setBounds(430, 360, 150, 50);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon("D:\\JAVA PRO\\bibliotecas.png")); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 780, 510);

        setSize(new java.awt.Dimension(790, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAluguelActionPerformed
        Aluguel aluguel = new Aluguel();
        aluguel.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonAluguelActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAluguel;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBB;
    private javax.swing.JLabel jLabelBem;
    private javax.swing.JLabel jLabelFundoPrincipal;
    // End of variables declaration//GEN-END:variables
}
